services:
  mysql:
    extends:
      file: docker-compose.infra.yaml
      service: mysql

  mongodb:
    extends:
      file: docker-compose.infra.yaml
      service: mongodb

  rabbitmq:
    extends:
      file: docker-compose.infra.yaml
      service: rabbitmq

  mongo-express:
    extends:
      file: docker-compose.infra.yaml
      service: mongo-express

  localstack:
    extends:
      file: docker-compose.infra.yaml
      service: localstack
  
  config-server:
    build: ./ConfigServer
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - mysql

  eureka-server:
    build: ./Eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server

  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  authentication:
    restart: on-failure
    build:
      context: ./authentication
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AuthenticationService?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      FRONTEND_URL: http://localhost:5173 # Frontend URL for development
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
