services:
  mysql:
    extends:
      file: docker-compose.infra.yaml
      service: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      timeout: 20s
      retries: 10
      start_period: 10s

  mongodb:
    extends:
      file: docker-compose.infra.yaml
      service: mongodb
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  rabbitmq:
    extends:
      file: docker-compose.infra.yaml
      service: rabbitmq

  mongo-express:
    extends:
      file: docker-compose.infra.yaml
      service: mongo-express

  localstack:
    extends:
      file: docker-compose.infra.yaml
      service: localstack

  config-server:
    build: ./ConfigServer
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config
    volumes:
      - ./config:/config # Mount your config directory here
    depends_on:
      - mysql

  eureka-server:
    build: ./Eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - config-server

  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  authentication:
    restart: on-failure
    build:
      context: ./authentication
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AuthenticationService?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      FRONTEND_URL: http://localhost:5173 # Frontend URL for development
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  email-service:
    build:
      context: ./EmailService
      dockerfile: Dockerfile
    container_name: email-service
    ports:
      - "8085:8085"
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      MAIL_USERNAME: YOUR_MAIL_USERNAME
      MAIL_PASSWORD: YOUR_MAIL_PASSWORD
      MAIL_HOST: YOUR_MAIL_HOST
      MAIL_PORT: YOUR_MAIL_PORT
    depends_on:
      - config-server
      - eureka-server
      - rabbitmq
    secrets:
      - email

secrets:
  email:
    file: ./secrets/mail.txt